@startuml

entity member {
    id (pk)
    ---
    first_name
    last_name
    email
    department_id (fk)
    }

    entity department {
    id (pk)
    ---
    name
    }

entity task {
    id (pk)
    ---
    name
    description
    status
}

entity task_member {
    id (pk)
    --
    task_id (fk)
    member_id (fk)
}

enum task_status {
    OPEN
    IN_PROGRESS
    FINISHED
    CANCELED
    }

member ||--o{ task_member
task ||--o{ task_member
task_status ||-- task
department |o--o{ member

@enduml