@startuml

actor User
participant WebBrowser

box Java Server
   participant HttpServer
   participant MemberGetController
   participant MemberDao
   participant AbstractDao
end box

database PostgreSQL

User -> WebBrowser: List members
WebBrowser -> HttpServer: /index.html
WebBrowser <-- HttpServer: <html>....<script>fetch()</html>
WebBrowser -> HttpServer: /api/member
HttpServer -> HttpServer: controllers.get("/api/products")
HttpServer -> MemberGetController: handle(HttpMessage request)
MemberGetController -> MemberDao: list()
MemberDao -> AbstractDao: list("SELECT * FROM member")
AbstractDao -> PostgreSQL: "SELECT * FROM member"
AbstractDao <-- PostgreSQL: ResultSet
MemberDao <- AbstractDao: mapRow(ResultSet)
MemberDao --> AbstractDao: Member
|||
AbstractDao --> MemberDao: List<T>
MemberGetController <-- MemberDao: List<member>
HttpServer <-- MemberGetController: [HttpMessage response]
WebBrowser <-- HttpServer: <ul></li><li>...<li>..</ul>
User <- WebBrowser: List of members

@enduml